apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: backtest-fanout
spec:
  entrypoint: backtest

  parallelism: 4

  arguments:
    parameters:
      - name: image_repo
        description: "Container image repo"
        value: ghcr.io/trading-engineering/trading-runtime

      - name: image_tag
        description: "Container image tag to run (recommended: commit SHA)"
        value: main

      - name: experiment_config
        description: "Path to experiment JSON inside the container"
        value: /usr/local/lib/python3.11/site-packages/trading_runtime/argo/argo.json

      - name: scratch_root
        description: "Scratch root inside the container"
        value: /mnt/scratch

  templates:
    - name: backtest
      dag:
        tasks:
          - name: plan
            template: plan

          - name: run-sweeps
            dependencies: [plan]
            template: run-sweep
            parallelism: 3
            withParam: "{{tasks.plan.outputs.parameters.sweep-list}}"
            arguments:
              parameters:
                - name: sweep-path
                  value: "{{item}}"

          - name: finalize-segments
            dependencies: [run-sweeps]
            template: segment-finalize
            withParam: "{{tasks.plan.outputs.parameters.segment-list}}"
            arguments:
              parameters:
                - name: experiment-id
                  value: "{{tasks.plan.outputs.parameters.experiment-id}}"

                - name: segment-id
                  value: "{{item.segment_id}}"

                - name: expected-sweeps
                  value: "{{item.expected_sweeps}}"

                - name: completed-sweeps
                  value: "{{item.expected_sweeps}}"

                - name: failed-sweeps
                  value: "0"

                - name: segment-started-at
                  value: "{{workflow.creationTimestamp}}"

                - name: scratch-root
                  value: "{{workflow.parameters.scratch_root}}"

          - name: finalize-experiment
            dependencies: [finalize-segments]
            template: experiment-finalize
            arguments:
              parameters:
                - name: experiment-id
                  value: "{{tasks.plan.outputs.parameters.experiment-id}}"

                - name: expected-segments
                  value: "{{tasks.plan.outputs.parameters.expected-segments}}"

                - name: completed-segments
                  value: "{{tasks.plan.outputs.parameters.expected-segments}}"

                - name: failed-segments
                  value: "0"

                - name: experiment-started-at
                  value: "{{workflow.creationTimestamp}}"

                - name: scratch-root
                  value: "{{workflow.parameters.scratch_root}}"

    - name: plan
      container:
        image: "{{workflow.parameters.image_repo}}:{{workflow.parameters.image_tag}}"
        imagePullPolicy: Always

        command: [python, -m]
        args:
          - trading_platform.backtest.runtime.entrypoint
          - --config
          - "{{workflow.parameters.experiment_config}}"
          - --run
          - --emit-dir
          - /mnt/scratch/sweeps/{{workflow.uid}}

        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"

        volumeMounts:
          - name: scratch
            mountPath: /mnt/scratch

      outputs:
        parameters:
          - name: experiment-id
            valueFrom:
              path: /mnt/scratch/sweeps/{{workflow.uid}}/experiment_id.txt

          - name: sweep-list
            valueFrom:
              path: /mnt/scratch/sweeps/{{workflow.uid}}/index.json

          - name: segment-list
            valueFrom:
              path: /mnt/scratch/sweeps/{{workflow.uid}}/segments.json

          - name: expected-segments
            valueFrom:
              path: /mnt/scratch/sweeps/{{workflow.uid}}/expected_segments.txt

    - name: run-sweep
      inputs:
        parameters:
          - name: sweep-path

      podMetadata:
        labels:
          sweep: "{{inputs.parameters.sweep-path | base }}"

      container:
        image: "{{workflow.parameters.image_repo}}:{{workflow.parameters.image_tag}}"
        imagePullPolicy: Always

        command: [python, -m]
        args:
          - trading_platform.backtest.runtime.run_sweep
          - --context
          - "{{inputs.parameters.sweep-path}}"
          - --scratch-root
          - "{{workflow.parameters.scratch_root}}"

        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"

        volumeMounts:
          - name: scratch
            mountPath: /mnt/scratch

    - name: segment-finalize
      inputs:
        parameters:
          - name: experiment-id
          - name: segment-id
          - name: expected-sweeps
          - name: completed-sweeps
          - name: failed-sweeps
          - name: segment-started-at
          - name: scratch-root

      container:
        image: "{{workflow.parameters.image_repo}}:{{workflow.parameters.image_tag}}"
        imagePullPolicy: Always

        env:
          - name: PROMETHEUS_PUSHGATEWAY_URL
            value: http://prometheus-pushgateway.monitoring.svc.cluster.local:9091

          - name: MLFLOW_TRACKING_URI
            value: http://mlflow-svc.mlflow.svc.cluster.local:5000

          - name: ARGO_WORKFLOW_UID
            value: "{{workflow.uid}}"

          - name: PROMETHEUS_PUSHGATEWAY_GROUPING_KEY_JSON
            value: '{"workflow_uid":"{{workflow.uid}}","segment_id":"{{inputs.parameters.segment-id}}"}'

        command: [python, -m]
        args:
          - trading_platform.backtest.runtime.segment_finalize_entrypoint

          - "--experiment-id"
          - "{{inputs.parameters.experiment-id}}"

          - "--segment-id"
          - "{{inputs.parameters.segment-id}}"

          - "--expected-sweeps"
          - "{{inputs.parameters.expected-sweeps}}"

          - "--completed-sweeps"
          - "{{inputs.parameters.completed-sweeps}}"

          - "--failed-sweeps"
          - "{{inputs.parameters.failed-sweeps}}"

          - "--segment-started-at"
          - "{{inputs.parameters.segment-started-at}}"

          - "--scratch-root"
          - "{{inputs.parameters.scratch-root}}"

        resources:
          requests:
            cpu: "0.5"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"

        volumeMounts:
          - name: scratch
            mountPath: /mnt/scratch

    - name: experiment-finalize
      inputs:
        parameters:
          - name: experiment-id
          - name: expected-segments
          - name: completed-segments
          - name: failed-segments
          - name: experiment-started-at
          - name: scratch-root

      container:
        image: "{{workflow.parameters.image_repo}}:{{workflow.parameters.image_tag}}"
        imagePullPolicy: Always

        env:
          - name: PROMETHEUS_PUSHGATEWAY_URL
            value: http://prometheus-pushgateway.monitoring.svc.cluster.local:9091

          - name: MLFLOW_TRACKING_URI
            value: http://mlflow-svc.mlflow.svc.cluster.local:5000

          - name: ARGO_WORKFLOW_UID
            value: "{{workflow.uid}}"

          - name: PROMETHEUS_PUSHGATEWAY_GROUPING_KEY_JSON
            value: '{"workflow_uid":"{{workflow.uid}}","scope":"experiment"}'

        command: [python, -m]
        args:
          - trading_platform.backtest.runtime.experiment_finalize_entrypoint

          - "--experiment-id"
          - "{{inputs.parameters.experiment-id}}"

          - "--expected-segments"
          - "{{inputs.parameters.expected-segments}}"

          - "--completed-segments"
          - "{{inputs.parameters.completed-segments}}"

          - "--failed-segments"
          - "{{inputs.parameters.failed-segments}}"

          - "--experiment-started-at"
          - "{{inputs.parameters.experiment-started-at}}"

          - "--scratch-root"
          - "{{inputs.parameters.scratch-root}}"

        resources:
          requests:
            cpu: "0.5"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"

        volumeMounts:
          - name: scratch
            mountPath: /mnt/scratch

  volumes:
    - name: scratch
      hostPath:
        path: /mnt/scratch
        type: Directory
